version: '3.8'

services:
  db:
    image: postgres:15
    container_name: group7_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: T74l82J04a12theb!
      POSTGRES_DB: group7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
